/**
 * Tests for CV text extraction: real PDF, fake PDF, scanned (textless) PDF, plain text, cap, unsupported type.
 *
 * Project: oldboys — goal-conditioned, sourced deep research on a person or company (Apify hackathon)
 * Module:  src/domain/__tests__/cv-text.test.ts
 * Deps:    vitest, unpdf (through the module under test)
 * Tested:  n/a (this is the test file)
 *
 * Key responsibilities:
 * - Cover specs/intake/funnel.md cv-text list; prove the input bytes survive extraction (they go to R2 next)
 *
 * Design constraints:
 * - The PDF is generated by fixtures/tiny-pdf.ts, no binary fixture
 */
import { describe, expect, it } from "vitest";
import { CV_MAX } from "../application";
import { extractCvText } from "../cv-text";
import { tinyPdf } from "./fixtures/tiny-pdf";

const enc = (s: string): ArrayBuffer => new TextEncoder().encode(s).buffer;

describe("extractCvText", () => {
  it("extracts and collapses whitespace from a real PDF", async () => {
    const bytes = tinyPdf("Josef   Buryan Kubernetes engineer");
    const out = await extractCvText({ bytes, contentType: "application/pdf", filename: "cv.pdf" });
    expect(out).toEqual({ text: "Josef Buryan Kubernetes engineer", note: null });
    expect(bytes.byteLength).toBeGreaterThan(0);
  });

  it("detects a PDF by filename when the content type is generic", async () => {
    const out = await extractCvText({ bytes: tinyPdf("Kubernetes"), contentType: "application/octet-stream", filename: "CV.PDF" });
    expect(out.text).toBe("Kubernetes");
  });

  it("notes a PDF without text", async () => {
    const out = await extractCvText({ bytes: tinyPdf(null), contentType: "application/pdf", filename: "scan.pdf" });
    expect(out).toEqual({ text: null, note: "PDF has no extractable text (scanned?)" });
  });

  it("notes bytes that claim to be PDF but lack the %PDF header", async () => {
    const out = await extractCvText({ bytes: enc("hello"), contentType: "application/pdf", filename: "cv.pdf" });
    expect(out.text).toBeNull();
    expect(out.note).toMatch(/not a PDF/);
  });

  it("turns a broken PDF into a note instead of throwing", async () => {
    const out = await extractCvText({ bytes: enc("%PDF-1.4 garbage"), contentType: "application/pdf", filename: "cv.pdf" });
    expect(out.text).toBeNull();
    expect(out.note).toMatch(/^PDF could not be read/);
  });

  it("passes plain text through, trimmed", async () => {
    const out = await extractCvText({ bytes: enc("  Ten years of Go.\n"), contentType: "text/plain; charset=utf-8", filename: "cv" });
    expect(out).toEqual({ text: "Ten years of Go.", note: null });
  });

  it("caps text at CV_MAX", async () => {
    const out = await extractCvText({ bytes: enc("x".repeat(CV_MAX + 50)), contentType: "", filename: "cv.txt" });
    expect(out.text).toHaveLength(CV_MAX);
  });

  it("notes an unsupported format", async () => {
    const out = await extractCvText({ bytes: enc("PK"), contentType: "application/msword", filename: "cv.doc" });
    expect(out).toEqual({ text: null, note: "unsupported CV format application/msword" });
  });
});
