/**
 * Tests for CV text extraction: real PDF, fake PDF, scanned (textless) PDF, Word (.docx), plain text, cap, old Word (.doc), unsupported type.
 *
 * Project: oldboys — goal-conditioned, sourced deep research on a person or company (Apify hackathon)
 * Module:  src/domain/__tests__/cv-text.test.ts
 * Deps:    vitest, unpdf and mammoth (through the module under test)
 * Tested:  n/a (this is the test file)
 *
 * Key responsibilities:
 * - Cover specs/intake/funnel.md cv-text list and the DOCX rules of specs/intake/apply-page.md;
 *   prove the input bytes survive extraction (they go to R2 next)
 * - The bytes' magic picks the parser over the declared type; a decompression bomb is a note, never parsed; text files
 *   in UTF-16 or windows-1250 are read, binary bytes named .txt are not text
 *
 * Design constraints:
 * - The PDF and the DOCX are generated by fixtures/tiny-pdf.ts and fixtures/tiny-docx.ts, no binary fixture
 */
import { describe, expect, it } from "vitest";
import { CV_MAX } from "../application";
import { extractCvText } from "../cv-text";
import { CV_MEDIA_TYPE } from "../cv-kind";
import { tinyDocx } from "./fixtures/tiny-docx";
import { tinyPdf } from "./fixtures/tiny-pdf";

const enc = (s: string): ArrayBuffer => new TextEncoder().encode(s).buffer;

/** UTF-16 little-endian code units of `s`, with the FF FE byte order mark when `bom`. */
function utf16le(s: string, bom: boolean): ArrayBuffer {
  const out: number[] = bom ? [0xff, 0xfe] : [];
  for (let i = 0; i < s.length; i++) out.push(s.charCodeAt(i) & 0xff, s.charCodeAt(i) >> 8);
  return new Uint8Array(out).buffer;
}

describe("extractCvText", () => {
  it("extracts and collapses whitespace from a real PDF", async () => {
    const bytes = tinyPdf("Josef   Buryan Kubernetes engineer");
    const out = await extractCvText({ bytes, contentType: "application/pdf", filename: "cv.pdf" });
    expect(out).toEqual({ text: "Josef Buryan Kubernetes engineer", note: null });
    expect(bytes.byteLength).toBeGreaterThan(0);
  });

  it("detects a PDF by filename when the content type is generic", async () => {
    const out = await extractCvText({ bytes: tinyPdf("Kubernetes"), contentType: "application/octet-stream", filename: "CV.PDF" });
    expect(out.text).toBe("Kubernetes");
  });

  it("notes a PDF without text", async () => {
    const out = await extractCvText({ bytes: tinyPdf(null), contentType: "application/pdf", filename: "scan.pdf" });
    expect(out).toEqual({ text: null, note: "PDF has no extractable text (scanned?)" });
  });

  it("notes bytes that claim to be PDF but lack the %PDF header", async () => {
    const out = await extractCvText({ bytes: enc("hello"), contentType: "application/pdf", filename: "cv.pdf" });
    expect(out.text).toBeNull();
    expect(out.note).toMatch(/not a PDF/);
  });

  it("turns a broken PDF into a note instead of throwing", async () => {
    const out = await extractCvText({ bytes: enc("%PDF-1.4 garbage"), contentType: "application/pdf", filename: "cv.pdf" });
    expect(out.text).toBeNull();
    expect(out.note).toMatch(/^PDF could not be read/);
  });

  it("passes plain text through, trimmed", async () => {
    const out = await extractCvText({ bytes: enc("  Ten years of Go.\n"), contentType: "text/plain; charset=utf-8", filename: "cv" });
    expect(out).toEqual({ text: "Ten years of Go.", note: null });
  });

  it("caps text at CV_MAX", async () => {
    const out = await extractCvText({ bytes: enc("x".repeat(CV_MAX + 50)), contentType: "", filename: "cv.txt" });
    expect(out.text).toHaveLength(CV_MAX);
  });

  it("stores an old Word (.doc) file without reading it", async () => {
    const out = await extractCvText({ bytes: enc("PK"), contentType: "application/msword", filename: "cv.doc" });
    expect(out).toEqual({ text: null, note: "old Word (.doc) file stored, not read" });
  });

  it("reads a UTF-16 text file by its BOM and a Czech windows-1250 one", async () => {
    expect((await extractCvText({ bytes: utf16le("Jiří Novák", true), contentType: "text/plain", filename: "cv.txt" })).text).toBe("Jiří Novák");
    const cp1250 = new Uint8Array([0x4a, 0x69, 0xf8, 0xed, 0x20, 0x4e, 0x6f, 0x76, 0xe1, 0x6b]); // "Jiří Novák"
    expect((await extractCvText({ bytes: cp1250.buffer, contentType: "text/plain", filename: "cv.txt" })).text).toBe("Jiří Novák");
  });

  it("notes binary bytes named .txt instead of passing them on as a CV", async () => {
    const binary = new Uint8Array(2000).map((_, i) => (i * 37) % 256);
    const out = await extractCvText({ bytes: binary.buffer, contentType: "text/plain", filename: "cv.txt" });
    expect(out).toEqual({ text: null, note: "CV text file is not readable text" });
    expect((await extractCvText({ bytes: utf16le("Ten years of Go.", false), contentType: "text/plain", filename: "cv.txt" })).text).toBeNull();
  });

  it("follows the bytes, not the declared type: a .docx sent as a PDF is read as Word", async () => {
    const out = await extractCvText({ bytes: tinyDocx(["Jana Novak"]), contentType: "application/pdf", filename: "cv.pdf" });
    expect(out).toEqual({ text: "Jana Novak", note: null });
  });

  it("notes an unsupported format", async () => {
    const out = await extractCvText({ bytes: enc("x"), contentType: "image/png", filename: "cv.png" });
    expect(out).toEqual({ text: null, note: "unsupported CV format image/png" });
  });
});

describe("extractCvText for Word (.docx)", () => {
  it("extracts and collapses whitespace from a real DOCX, leaving the input bytes intact", async () => {
    const bytes = tinyDocx(["Jana   Novak", "Go & Kubernetes engineer"]);
    const size = bytes.byteLength;
    const out = await extractCvText({ bytes, contentType: CV_MEDIA_TYPE.docx, filename: "jana.docx" });
    expect(out).toEqual({ text: "Jana Novak Go & Kubernetes engineer", note: null });
    expect(bytes.byteLength).toBe(size);
  });

  it("detects a DOCX by filename when the content type is generic", async () => {
    const out = await extractCvText({ bytes: tinyDocx(["Rust"]), contentType: "application/octet-stream", filename: "CV.DOCX" });
    expect(out.text).toBe("Rust");
  });

  it("notes a DOCX without text", async () => {
    const out = await extractCvText({ bytes: tinyDocx([]), contentType: CV_MEDIA_TYPE.docx, filename: "empty.docx" });
    expect(out).toEqual({ text: null, note: "Word file has no readable text" });
  });

  it("notes bytes with a .docx name that are not a ZIP", async () => {
    const out = await extractCvText({ bytes: enc("hello"), contentType: "", filename: "cv.docx" });
    expect(out).toEqual({ text: null, note: "not a Word file (no ZIP header)" });
  });

  it("turns a broken ZIP into a note instead of throwing", async () => {
    const out = await extractCvText({ bytes: enc("PK garbage"), contentType: CV_MEDIA_TYPE.docx, filename: "cv.docx" });
    expect(out.text).toBeNull();
    expect(out.note).toMatch(/^Word file could not be read: /);
  });

  it("reads a deflated DOCX, as Word writes it", async () => {
    const out = await extractCvText({ bytes: tinyDocx(["Jana Novak"], { deflate: true }), contentType: CV_MEDIA_TYPE.docx, filename: "cv.docx" });
    expect(out).toEqual({ text: "Jana Novak", note: null });
  });

  it("never parses a DOCX or PDF that would inflate past the cap", async () => {
    const pad = 48 * 1024 * 1024;
    const docx = await extractCvText({ bytes: tinyDocx(["Jana"], { pad }), contentType: CV_MEDIA_TYPE.docx, filename: "cv.docx" });
    expect(docx).toEqual({ text: null, note: "Word file would inflate past 40 MB, not read" });
    const pdf = await extractCvText({ bytes: tinyPdf("Josef", { deflate: true, pad }), contentType: "application/pdf", filename: "cv.pdf" });
    expect(pdf).toEqual({ text: null, note: "PDF would inflate past 40 MB, not read" });
  });

  it("caps DOCX text at CV_MAX", async () => {
    const out = await extractCvText({ bytes: tinyDocx(["y".repeat(CV_MAX + 50)]), contentType: CV_MEDIA_TYPE.docx, filename: "cv.docx" });
    expect(out.text).toHaveLength(CV_MAX);
  });
});
