/**
 * Deployed Worker entry: OpenNext's generated fetch handler plus the Workflow class export.
 *
 * Project: oldboys — goal-conditioned, sourced deep research on a person or company (Apify hackathon)
 * Module:  src/worker.ts
 * Deps:    .open-next/worker.js (generated by `opennextjs-cloudflare build`)
 * Tested:  n/a (verified by `wrangler deploy --dry-run`)
 *
 * Key responsibilities:
 * - Re-use the generated Next.js fetch handler unchanged
 * - Export ResearchRunWorkflow so wrangler can bind it (workflows[].class_name)
 *
 * Design constraints:
 * - Documented OpenNext "custom worker" pattern (opennext.js.org/cloudflare/howtos/custom-worker);
 *   wrangler.jsonc `main` points here, not at .open-next/worker.js
 * - Add other handlers (scheduled, queue) here, never inside the Next.js app
 */
// @ts-ignore: .open-next/worker.js exists only after `opennextjs-cloudflare build`
import { default as nextHandler } from "../.open-next/worker.js";

export { ResearchRunWorkflow } from "@/workflow/research-run";

export default {
  fetch: nextHandler.fetch,
} satisfies ExportedHandler<CloudflareEnv>;
