/**
 * Deployed Worker entry: OpenNext's generated fetch handler, the cron and email handlers, and the Workflow class exports.
 *
 * Project: oldboys — goal-conditioned, sourced deep research on a person or company (Apify hackathon)
 * Module:  src/worker.ts
 * Deps:    .open-next/worker.js (generated by `opennextjs-cloudflare build`), src/workflow/purge,
 *          src/workflow/intake-email, src/workflow/intake (retryCappedApplications)
 * Tested:  n/a (verified by `wrangler deploy --dry-run`)
 *
 * Key responsibilities:
 * - Re-use the generated Next.js fetch handler unchanged
 * - Export ResearchRunWorkflow and VerificationCallWorkflow so wrangler can bind it (workflows[].class_name)
 * - `scheduled`: the nightly cron purges expired raw payloads, the quarter-hour cron starts the runs of capped intake
 *   applications once the hourly cap has room; `email`: Email Routing intake (jobs[+tag]@asajj.cz, specs/intake/email.md)
 *
 * Design constraints:
 * - Documented OpenNext "custom worker" pattern (opennext.js.org/cloudflare/howtos/custom-worker);
 *   wrangler.jsonc `main` points here, not at .open-next/worker.js
 * - Other handlers (scheduled purge, email intake) live here, never inside the Next.js app; each is a one-line
 *   call into src/workflow so it stays testable without the Workers runtime
 */
// @ts-ignore: .open-next/worker.js exists only after `opennextjs-cloudflare build`
import { default as generated } from "../.open-next/worker.js";

// The generated module is untyped before the build runs; pin the shape we rely on.
const nextHandler = generated as { fetch: NonNullable<ExportedHandler<CloudflareEnv>["fetch"]> };

export { ResearchRunWorkflow } from "@/workflow/research-run";
export { VerificationCallWorkflow } from "@/workflow/verification-call";
import { purgeExpired } from "@/workflow/purge";
import { handleIntakeEmail } from "@/workflow/intake-email";
import { retryCappedApplications } from "@/workflow/intake";

/** Must equal the nightly entry of `triggers.crons` in wrangler.jsonc; every other cron is the capped-intake queue. */
const PURGE_CRON = "0 3 * * *";

export default {
  fetch: nextHandler.fetch,
  // Crons in wrangler.jsonc: raw payloads past their 7-day TTL are purged nightly (hackathon rule, and the privacy line
  // on Screen 1); capped applications are queued, not refused, so the quarter-hour cron starts their runs
  scheduled: async (event, env) => {
    if (event.cron === PURGE_CRON) await purgeExpired(env.DB, env.SOURCES, new Date());
    else await retryCappedApplications(env, new Date());
  },
  // Email Routing (rule jobs@ plus the zone catch-all) -> one application per mail; other recipients are rejected inside
  email: async (message, env) => {
    await handleIntakeEmail(message, env, new Date(), (line) => {
      console.warn(line);
    });
  },
} satisfies ExportedHandler<CloudflareEnv>;
