/**
 * Deployed Worker entry: OpenNext's generated fetch handler plus the Workflow class export.
 *
 * Project: oldboys — goal-conditioned, sourced deep research on a person or company (Apify hackathon)
 * Module:  src/worker.ts
 * Deps:    .open-next/worker.js (generated by `opennextjs-cloudflare build`)
 * Tested:  n/a (verified by `wrangler deploy --dry-run`)
 *
 * Key responsibilities:
 * - Re-use the generated Next.js fetch handler unchanged
 * - Export ResearchRunWorkflow and VerificationCallWorkflow so wrangler can bind it (workflows[].class_name)
 *
 * Design constraints:
 * - Documented OpenNext "custom worker" pattern (opennext.js.org/cloudflare/howtos/custom-worker);
 *   wrangler.jsonc `main` points here, not at .open-next/worker.js
 * - Other handlers (scheduled purge) live here, never inside the Next.js app
 */
// @ts-ignore: .open-next/worker.js exists only after `opennextjs-cloudflare build`
import { default as generated } from "../.open-next/worker.js";

// The generated module is untyped before the build runs; pin the shape we rely on.
const nextHandler = generated as { fetch: NonNullable<ExportedHandler<CloudflareEnv>["fetch"]> };

export { ResearchRunWorkflow } from "@/workflow/research-run";
export { VerificationCallWorkflow } from "@/workflow/verification-call";
import { purgeExpired } from "@/workflow/purge";

export default {
  fetch: nextHandler.fetch,
  // Cron in wrangler.jsonc: raw payloads past their 7-day TTL are purged (hackathon rule, and the privacy line on Screen 1)
  scheduled: async (_event, env) => {
    await purgeExpired(env.DB, env.SOURCES, new Date());
  },
} satisfies ExportedHandler<CloudflareEnv>;
